# config/train_config.yaml

num_frames: 5
input_shape: [5, 84, 84]

num_episodes: 500
max_steps_per_episode: 1000

gamma: 0.99

epsilon:
  start: 1.0
  decay: 0.995
  min: 0.1

batch_size: 32
learning_rate: 0.0001

replay_capacity: 10000
target_update_interval: 10
save_interval: 50
