# config/train_config.yaml

num_frames: 5
channels_per_frame: 3
input_shape_2d: [128, 128]

num_episodes: 1000
max_steps_per_episode: 1000

gamma: 0.99

epsilon:
  start: 1.0
  decay: 0.995
  min: 0.1

batch_size: 32
learning_rate: 0.0005

replay_capacity: 2000
target_update_interval: 10
save_interval: 50

eval_episodes: 10
init_model_path: "models/policy_net_1000_1914_29092025.pth"