# config/train_config.yaml

num_frames: 5
channels_per_frame: 3
input_shape_2d: [128, 128]
n_actions: 5

max_frames: 100000000
max_steps_per_episode: 4000
num_asteroids: 4
max_asteroid_size: 90
max_asteroid_speed: 2.0

gamma: 0.99

# epsilon:
#   start: 1.0
#   decay: 0.997
#   min: 0.1

batch_size: 64
learning_rate: 0.0001

replay_capacity: 20000
target_update_interval: 50000
save_interval: 100000
log_interval: 20000

alpha: 0.6
beta_start: 0.4

num_envs: 16

eval_episodes: 5
init_model_path: ""